[package]
name = "dale"
version = "0.1.0"
authors = ["Artur Wyszy≈Ñski <artur.wyszynski@hitomi.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
